version: '3'

tasks:
  ###
  # CI
  ###
  ci-style-check:
    desc: runs both ruff check and ruff format on the current WD
    cmds:
      - ruff check .
      - ruff format .

  ci-type-check:
    desc: runs mypy type checking on the current WD
    cmds:
      - mypy .

  ci:
    desc: Runs all CI checks [linting, formatting, type checking, and lock file integrety]
    sources:
      - src/**/*.py
      - tests/**/*.py
    cmds:
      - task: ci-style-check
      - task: ci-type-check
      - poetry lock --check --quiet
